version: "3"

services:
  scrape-calendar-data:
    container_name: scrape-calendar-data
    image: Scrape-Calendar-Data
    network_mode: "host"
    volumes:
      - ~/secrets:/scrapeCalendarData/secrets
  server-monitor:
    container_name: server-monitor
    image: Server-Monitor
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ~/secrets:/serverMonitor/secrets
  status-lights:
    container_name: status-lights
    privileged: true
    image: ghsapp/status-lights
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ~/secrets:/statusLights/secrets
