apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghsapp-scrape-calendar-data
spec:
  selector:
    matchLabels:
      ghsAppComponent: scrape-calendar-data
  template:
    metadata:
      labels:
        ghsAppComponent: scrape-calendar-data
    spec:
      containers:
        - name: scrape-calendar-data
          image: ghsApp/scape-calendar-data:arm32v7