apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghsapp-scrape-calendar-data
spec:
  selector:
    matchLabels:
      ghsAppComponent: scrape-calendar-data
  template:
    metadata:
      labels:
        ghsAppComponent: scrape-calendar-data
    spec:
      containers:
        - name: scrape-calendar-data
          image: ghsapp/scape-calendar-data:arm32v7
          volumeMounts:
            - mountPath: /src/secrets
              name: secrets-volume
          resources:
              requests:
                memory: "400Mi"
                cpu: "300m"
              limits:
                memory: "500Mi"
                cpu: "500m"
      volumes:
        - name: secrets-volume
          hostPath:
            path: ~/secrets
            type: Directory