apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghsapp-server-monitor
spec:
  selector:
    matchLabels:
      ghsAppComponent: scrape-calendar-data
  template:
    metadata:
      labels:
        ghsAppComponent: scrape-calendar-data
    spec:
      containers:
        - name: scrape-calendar-data
          image: ghsapp/scape-calendar-data:arm32v7
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "400Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: secrets
          hostPath:
            path: ~/secrets
            type: Directory